name: Build executables

on:
  push:
    tags:
      - "**"

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            exe_src_name: setup.exe
            exe_target_name: gt2_discs_combiner.exe
            zip_cmd: tar -c -f gt2_discs_combiner_${{ github.ref_name }}_windows.zip -C setup.dist *
          - os: ubuntu-latest
            exe_src_name: setup
            exe_target_name: gt2_discs_combiner
            zip_cmd: zip -r gt2_discs_combiner_${{ github.ref_name }}_linux.zip setup.dist
    steps:
      - name: Setup python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Checkout this repo's source code
        uses: actions/checkout@v2
      - name: Checkout the GTModTools repo
        uses: actions/checkout@v2
        with:
          repository: CookiePLMonster/GTModTools
          path: gttools
      - name: Install nuitka
        run: pip install Nuitka==0.7.2
      - name: Compile into an executable
        run: python -m nuitka --standalone `
          --include-data-dir=menu_entries=menu_entries `
          --include-data-dir=tools=tools `
          --include-data-dir=vol_replacements=vol_replacements `
          --enable-plugin=tk-inter `
          --assume-yes-for-downloads `
          setup.py
      - name: Rename the executable
        run: mv setup.dist/${{ matrix.exe_src_name }} setup.dist/${{ matrix.exe_target_name }}
        shell: bash
      - name: Package the build into a zip file
        run:
          ${{ matrix.zip_cmd }}
          # |
          # if [ "$RUNNER_OS" == "Linux" ]; then
          # zip -r gt2_discs_combiner_${{ github.ref_name }}_${{ matrix.os }}.zip setup.dist
          # elif [ "$RUNNER_OS" == "Windows" ]; then
          # tar -c -f gt2_discs_combiner_${{ github.ref_name }}_${{ matrix.os }}.zip -C setup.dist *
          # else
          # echo "$RUNNER_OS not supported"
          # exit 1
          # fi
        shell: bash
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: gt2_discs_combiner_${{ github.ref_name }}_${{ matrix.os }}.zip
